# Generated by Django 5.0.3 on 2024-03-09 18:55

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_member_programme_alter_member_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="contact",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="eg. +91 96XXXXXXX",
                max_length=128,
                region=None,
                unique=True,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="roll",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="roll number"
            ),
        ),
    ]
