# Generated by Django 5.0.3 on 2024-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_member_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
