# Generated by Django 5.0.3 on 2024-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_alter_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
