# Generated by Django 5.0.3 on 2024-04-11 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_alter_invitation_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
