# Generated by Django 5.0.3 on 2024-04-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('exit', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Q', 'QUEUED'), ('P', 'PROCESSING'), ('F', 'FINISHED')], default='Q', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.task')),
                ('email', models.EmailField(max_length=100)),
                ('task_function_id', models.PositiveSmallIntegerField(default=1)),
            ],
            bases=('home.task',),
        ),
    ]
