# Generated by Django 5.0.3 on 2024-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='task_function_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_function_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
