# Generated by Django 5.0.3 on 2024-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_sendemail_task_function_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_function_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
