# Generated by Django 5.0.3 on 2024-04-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_task_function_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendEmail',
            new_name='SendEmailTask',
        ),
    ]
