# Generated by Django 5.0.3 on 2024-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_sendemail_sendemailtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Q', 'QUEUED'), ('P', 'PROCESSING'), ('F', 'FINISHED'), ('A', 'ABORTED')], default='Q', max_length=1),
        ),
    ]
