# Generated by Django 5.0.3 on 2024-04-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_task_state'),
        ('members', '0013_alter_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendInviteTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.task')),
                ('invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.invitation')),
            ],
            bases=('home.task',),
        ),
        migrations.DeleteModel(
            name='SendEmailTask',
        ),
    ]
